### ISSUE TITLE
Can’t power on or off the TV

### ISSUE THREAD

**Issue by ojoaosemtil** [vniehues/saphi_tv_enhanced#1]
Hello!
First of all, thank you for this amazing plugin!
After the last updates, the ambi+hue works very well, but now I can’t turn on or off the TV, did you made any changes in the code? This was the only plugin working well..
Any plans to fix it?

Thank u!

**Comment by vniehues** [comment]
Hi @ojoaosemtil ! :) 
Thanks for the kind words. I have the plugin fully working in my home right now.
Can you please share your platform config? I'll try to help you based on that.

I do not plan any more updates to this plugin because im currently rewriting it from scratch to 
support things like the UI-Config Editor and allowing things like switching between sources, apps and maybe even channels.

But that might take some time to finish so if you provide your config I might help earlier :)

**Comment by ojoaosemtil** [comment]
Thank you for your reply!
Right now, I reversed to version 0.0.59 and have everything working properly.

I use the base config you provide:

    {
            "platform": "PhilipsSaphiTV",
            "name": "TV",
            "ip_address": "192.168.1.78",
            "model_year": "2018",
            "has_ambilight": true,
            "model_name": "43PUS6753/12",
            "model_serial_no": "123-456-ABC",
            "wol_url": "wol://C4:98:5C:FE:93:4C",
            "inputs": [
                {
                    "id": "hdmi1",
                    "name": "HDMI 1"
                },
                {
                    "id": "hdmi2",
                    "name": "Soundbar"
                },
                {
                    "id": "hdmi3",
                    "name": "HDMI 3"
                }
            ]
        },

**Comment by vniehues** [comment]
If you have it working like you want it right now I would advise you to stay on this exact setup. 
Frankly I don’t know what differences there are between 59 and latest because I did some rapid-releases for testing (never intended anyone else to use my plugin haha). 

I will keep you updated when a new plugin is available.

**Comment by ojoaosemtil** [comment]
Ahah great, it is working perfectly this way for me!
Thank you so much! I’ve been looking for a plug-in to work with my TV for months, none of them can turn on and off (only do one of the commands) and this ambilight+hue integration is perfect!

I’ll be waiting for that new plugin!

**Comment by vniehues** [comment]
Do you have any "must-have" features i should look into?

**Comment by ojoaosemtil** [comment]
Well, right now I only need to turn it on and off, the Ambilight+hue is great, all the rest I use an Apple TV for the apps.

But It would be nice to be able to turn on and off Ambilight, not the TV itself, choose the styles and the way it acts: follow video, audio, etc.
But it’s just a plus, right now, for me, it’s perfect!

**Comment by vniehues** [comment]
Thanks for your input! I will be looking into controlling the TVs built-in ambilight :)
I will now close this issue. If you have any feature requests, please open a new issue for that.
